# steps:
# # This step deploys the new version of our container image.
# # in the hello-cloudbuild Kubernetes Engine cluster.

# - name: 'gcr.io/cloud-builders/kubectl'
#   id: Deploy
#   args:
#   - 'apply'
#   - '-f'
#   - 'k8s.yaml'
#   env:
#   - 'CLOUDSDK_COMPUTE_REGION=asia-south1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=sheetal-gke'


steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
  '-c',
  'docker pull gcr.io/$PROJECT_ID/nginx-image:latest || exit 0'
 ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
  'build',
  '-t',
  'us-central1-docker.pkg.dev/$PROJECT_ID/priya-python-repo/nginx-image',
  '-t',
  'us-central1-docker.pkg.dev/$PROJECT_ID/priya-python-repo/nginx-image:latest',
  '.'
 ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sheetal-gke'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
  'set',
  'image',
  'deployment',
  'hello-cloudbuild',
  'hello-cloudbuild=us-central1-docker.pkg.dev/$PROJECT_ID/priya-python-repo/python-image'
 ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sheetal-gke'

# push images to Google Container Registry with tags
images: [
  'gcr.io/$PROJECT_ID/hello-cloudbuild:$TAG_NAME',
  'gcr.io/$PROJECT_ID/hello-cloudbuild:latest'
 ]


