steps:
# This step deploys the new version of our container image.
# in the hello-cloudbuild Kubernetes Engine cluster.

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'k8s.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sheetal-gke'

 
