 # Create the new instance template
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: create-instance-template
  args:
    - compute
    - instance-templates
    - create-with-container
    - priya-cloud-build-instance-template-v2-$_ENV-$SHORT_SHA
    - --custom-cpu=1
    - --custom-memory=2GB
    - --boot-disk-size=20GB
    - --region=us-central1
    - --subnet=mig-subnet
    - --tags=allow-hc-and-proxy,allow-ssh
    - --machine-image
    - priya-machine-image
 
    
 # Update the managed instance group


- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c','gcloud compute instance-groups managed rolling-action start-update priya-cloudbuild-mig --version=template=priya-cloud-build-instance-template-v2-$_ENV-$SHORT_SHA --region=us-central1 --max-unavailable=0'] 
  
options:
 logging: CLOUD_LOGGING_ONLY
